### ISSUE TITLE
发现ROM中开发APP进行debug调试触发断点就崩溃了

### ISSUE THREAD

**Issue by df13954** [dqzg12300/MikRom#45]
环境：aosp10r2代码，编译成功后刷入到pixel3
as创建普通项目在项目中随便打个断点，或者某个点击事件中打断点。
1：用debug模式启动App，无法进入APP中，一直卡主等待调试页面。
2：中途附加模式，APP运行中，点击as附加到开发的APP中，附近成功了，触发断点代码的时候崩溃。

```shell
909-909/? D/android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
1094-1094/? W/adbd: timeout expired while flushing socket, closing
1376-6568/system_process W/NotificationService: Toast already killed. pkg=com.example.myjike callback=android.app.ITransientNotification$Stub$Proxy@1481bdd
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
1376-3524/system_process E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
1376-1438/system_process W/WindowManager: Unable to start animation, surface is null or no children.
847-4706/? I/netd: trafficSwapActiveStatsMap() <0.57ms>
847-4706/? I/netd: tetherGetStats() <4.71ms>
1376-1449/system_process D/KernelCpuUidUserSysTimeReader: Removing uids 99005-99005
1376-1449/system_process D/KernelCpuUidUserSysTimeReader: Removing uids 90000-90000
1376-1449/system_process D/KernelCpuUidUserSysTimeReader: Removing uids 99006-99006
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
11430-11430/com.example.myjike D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
11430-11430/com.example.myjike E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myjike, PID: 11430
    java.lang.RuntimeException: Main thread loop unexpectedly exited
        at android.app.ActivityThread.main(ActivityThread.java:7380)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
1376-11474/system_process I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
1376-6566/system_process W/ActivityTaskManager:   Force finishing activity com.example.myjike/.MainActivity
1376-1436/system_process I/ActivityManager: Showing crash dialog for package com.example.myjike u0
1376-4969/system_process E/libc: Access denied finding property "vendor.debug.egl.changepixelformat"
1376-4969/system_process E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
1376-4969/system_process E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
1376-1438/system_process W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{1d18cc7 u0 com.example.myjike/.MainActivity t26 f}
1376-1438/system_process W/ActivityTaskManager: Activity pause timeout for ActivityRecord{1d18cc7 u0 com.example.myjike/.MainActivity t26 f}
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
904-904/? I//vendor/bin/hw/android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
1376-1376/system_process W/WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@684faa7
910-1027/? D/ASH: @ 2039.861: AP has been up: last 1739518271, now 2039861363 usec
910-1027/? D/ASH: @ 2039.863: Sending to ASH storage: 0 189 0

```

**Comment by df13954** [comment]
尝试过其他项目也是触发断点就崩溃了

**Comment by dqzg12300** [comment]
当前版本确实存在这个问题，排查过一段时间没找到问题。后面我做了个基于AOSP12的新版本，一些功能的调用方式调整后，没有看到这个问题了。不知道是因为AOSP10上被改动什么出现的，还是我调整调用方式被修复的。

**Comment by df13954** [comment]
> 当前版本确实存在这个问题，排查过一段时间没找到问题。后面我做了个基于AOSP12的新版本，一些功能的调用方式调整后，没有看到这个问题了。不知道是因为AOSP10上被改动什么出现的，还是我调整调用方式被修复的。

大佬啥时候会释放12系统的，放个测试版也行，毕竟断点调试没有了很难受....

**Comment by dqzg12300** [comment]
最快也要到下半年吧。尽量做完善了先。
